module.exports.errorHandler = require('./errorHandler')
module.exports.validateRegistration = require('./auth/validateRegistration')
module.exports.validateLogin = require('./auth/validateLogin')
module.exports.validateProduct = require('./products/validateProduct')
module.exports.isAuth = require('./auth/isAuth')
module.exports.JwtHandler = require('./JWT/JwtHandler')
